/*
 * SPDX-FileCopyrightText: 2026 KOKA99CAB
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

package net.koka99cab.portals.world;

import net.koka99cab.portals.PortalsMod;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.dimension.LevelStem;

public final class ModDimensions {
	public static final ResourceKey<Level> ORE_CAVES = ResourceKey.create(Registries.DIMENSION, PortalsMod.id("ore_caves"));
	public static final ResourceKey<LevelStem> ORE_CAVES_STEM = ResourceKey.create(Registries.LEVEL_STEM, PortalsMod.id("ore_caves"));
	public static final ResourceKey<Level> OVERWORLD2 = ResourceKey.create(Registries.DIMENSION, PortalsMod.id("overworld2"));
	public static final ResourceKey<LevelStem> OVERWORLD2_STEM = ResourceKey.create(Registries.LEVEL_STEM, PortalsMod.id("overworld2"));
	public static final ResourceKey<Level> SHEEP_LAND = ResourceKey.create(Registries.DIMENSION, PortalsMod.id("sheep_land"));
	public static final ResourceKey<LevelStem> SHEEP_LAND_STEM = ResourceKey.create(Registries.LEVEL_STEM, PortalsMod.id("sheep_land"));
	public static final ResourceKey<Level> SKELETON_WASTE = ResourceKey.create(Registries.DIMENSION, PortalsMod.id("skeleton_waste"));
	public static final ResourceKey<LevelStem> SKELETON_WASTE_STEM = ResourceKey.create(Registries.LEVEL_STEM, PortalsMod.id("skeleton_waste"));
	public static final ResourceKey<Level> PAINTED_CANYONS = ResourceKey.create(Registries.DIMENSION, PortalsMod.id("painted_canyons"));
	public static final ResourceKey<LevelStem> PAINTED_CANYONS_STEM = ResourceKey.create(Registries.LEVEL_STEM, PortalsMod.id("painted_canyons"));

	private ModDimensions() {
	}

	public static void init() {
		PortalsMod.LOGGER.debug("Registered dimension keys for {}, {}, {}, {}, and {}", ORE_CAVES.identifier(), OVERWORLD2.identifier(), SHEEP_LAND.identifier(), SKELETON_WASTE.identifier(), PAINTED_CANYONS.identifier());
	}
}
